#!/usr/bin/env bash

echo "Creating symlink to your oh-my-zsh themes path..."

mkdir -p ~/.oh-my-zsh/custom/themes/
ln -f sceal.zsh-theme ~/.oh-my-zsh/custom/themes/sceal.zsh-theme

echo "Sceal Theme successfually installed"
